export const legalContent = {
  ro: {
    privacy: {
      title: 'Politică de confidențialitate',
      description: 'Cum sunt colectate, utilizate și protejate datele cu caracter personal pe techcub.ro.',
      updated: 'Ultima actualizare: august 2026',
      sections: [
        { title: '1. Operatorul datelor', paragraphs: ['Operatorul datelor este {LEGAL_NAME}, CUI {CUI}, nr. de înregistrare {REGISTRATION}, cu sediul în {ADDRESS}. Pentru întrebări privind datele personale mă poți contacta la <a href="mailto:{EMAIL}">{EMAIL}</a> sau la {PHONE}.'] },
        { title: '2. Datele colectate', paragraphs: ['Prin formularul de contact pot fi colectate numele, adresa de e-mail, subiectul și conținutul mesajului. Dacă mă contactezi prin telefon, WhatsApp sau rețele sociale, prelucrez datele pe care alegi să le comunici. Pentru abonarea la newsletter este prelucrată adresa de e-mail.'] },
        { title: '3. Scopul și temeiul prelucrării', paragraphs: ['Datele sunt utilizate pentru a răspunde solicitărilor, a pregăti și executa serviciile convenite, a transmite newsletterul solicitat și a îndeplini obligațiile legale. Temeiul poate fi demersul făcut la cererea ta înaintea unui contract, executarea contractului, consimțământul sau obligația legală, după caz.'] },
        { title: '4. Furnizori și transferuri', paragraphs: ['Formularul și newsletterul pot utiliza Resend pentru transmiterea mesajelor și administrarea abonărilor. Furnizorii tehnici prelucrează datele numai pentru serviciile necesare funcționării site-ului. Atunci când datele sunt transferate în afara Spațiului Economic European, sunt utilizate mecanismele de protecție prevăzute de GDPR.'] },
        { title: '5. Durata păstrării', paragraphs: ['Solicitările sunt păstrate atât timp cât este necesar pentru răspuns și pentru relația contractuală, apoi conform termenelor legale aplicabile. Datele pentru newsletter sunt păstrate până la dezabonare sau retragerea consimțământului.'] },
        { title: '6. Drepturile tale', paragraphs: ['Ai dreptul de acces, rectificare, ștergere, restricționare, opoziție și portabilitate, precum și dreptul de a retrage consimțământul. Poți transmite o solicitare la <a href="mailto:{EMAIL}">{EMAIL}</a>. Dacă apreciezi că drepturile tale au fost încălcate, poți depune o plângere la <a href="https://www.dataprotection.ro/" target="_blank" rel="noopener noreferrer">ANSPDCP</a>.'] },
        { title: '7. Cookie-uri și statistici', paragraphs: ['Site-ul nu activează cookie-uri neesențiale fără consimțământ atunci când acestea sunt configurate. Politica va fi actualizată dacă sunt introduse servicii noi de analiză, marketing sau integrare care modifică modul de prelucrare a datelor.'] },
      ],
    },
    terms: {
      title: 'Termeni și condiții',
      description: 'Condițiile generale aplicabile utilizării site-ului și serviciilor Tech cu Bogdan.',
      updated: 'Ultima actualizare: august 2026',
      sections: [
        { title: '1. Furnizorul serviciilor', paragraphs: ['Serviciile prezentate pe techcub.ro sunt oferite de {LEGAL_NAME}, CUI {CUI}, nr. de înregistrare {REGISTRATION}, cu sediul în {ADDRESS}. Contact: <a href="mailto:{EMAIL}">{EMAIL}</a>, {PHONE}.'] },
        { title: '2. Rolul site-ului și încheierea contractului', paragraphs: ['Site-ul prezintă servicii de dezvoltare web, service calculatoare, suport IT și administrare IT. Informațiile publicate au caracter general și nu constituie singure o ofertă contractuală fermă.', 'Un contract se consideră încheiat când părțile confirmă în scris lucrarea, obiectul, prețul sau modul de calcul și, după caz, termenul. Oferta, comanda acceptată sau contractul individual prevalează dacă diferă de acești termeni.'] },
        { title: '3. Serviciile și termenele', paragraphs: ['Etapele, livrabilele, intervențiile incluse și serviciile recurente se stabilesc pentru fiecare lucrare. Activitățile suplimentare se execută numai după informarea clientului și acceptarea costului.', 'Termenele presupun furnizarea la timp a accesului, informațiilor, materialelor și aprobărilor necesare. Întârzierile cauzate de lipsa acestora pot decala termenul.'] },
        { title: '4. Prețul, piesele și licențele', paragraphs: ['Prețul și condițiile de plată sunt cele confirmate clientului. Piesele, licențele, abonamentele și serviciile terților nu sunt incluse decât dacă este menționat expres. Înlocuirea componentelor și depășirea estimării se fac numai cu acordul clientului.'] },
        { title: '5. Obligațiile clientului', paragraphs: ['Clientul trebuie să ofere informații corecte, să dețină drepturile necesare asupra echipamentelor, conturilor, datelor și materialelor puse la dispoziție și să păstreze copii de siguranță actuale înaintea intervenției, dacă realizarea backupului nu a fost convenită expres.'] },
        { title: '6. Garanție și răspundere', paragraphs: ['Pentru lucrările de service se acordă o garanție comercială de 30 de zile pentru manoperă, fără a limita garanțiile legale aplicabile. Garanția nu acoperă defecte diferite, defecțiuni preexistente, utilizare necorespunzătoare, intervenții ulterioare ale altor persoane sau componente furnizate de client.', 'Serviciile sunt prestate în limitele convenite. Furnizorul nu răspunde pentru restricțiile producătorilor ori indisponibilitatea serviciilor terților. Nicio prevedere nu limitează drepturile care nu pot fi excluse prin lege.'] },
        { title: '7. Dezvoltare web și proprietate intelectuală', paragraphs: ['Clientul răspunde pentru legalitatea materialelor furnizate. Drepturile asupra livrabilelor realizate special se transmit sau se licențiază conform ofertei și după plata integrală. Componentele preexistente și materialele terților rămân supuse licențelor proprii.'] },
        { title: '8. Dreptul de retragere', paragraphs: ['Consumatorul care încheie la distanță sau în afara spațiilor comerciale un contract pentru servicii beneficiază, în condițiile legii, de dreptul de retragere în 14 zile. Dacă solicită începerea serviciului în această perioadă, datorează suma proporțională cu partea executată. Dreptul se poate pierde după executarea integrală, cu acordul prealabil expres și confirmarea consecinței.'] },
        { title: '9. Reclamații și litigii', paragraphs: ['Sesizările pot fi transmise la <a href="mailto:{EMAIL}">{EMAIL}</a>. Consumatorii pot apela la <a href="https://anpc.ro/" target="_blank" rel="noopener noreferrer">ANPC</a> și la platforma de <a href="https://reclamatiisal.anpc.ro/" target="_blank" rel="noopener noreferrer">soluționare alternativă a litigiilor (SAL)</a>. Se aplică legea română, fără afectarea normelor imperative de protecție a consumatorului.'] },
        { title: '10. Actualizarea termenilor', paragraphs: ['Termenii pot fi actualizați când se modifică serviciile sau cadrul legal. Versiunea aplicabilă unui contract este cea acceptată la încheierea sa; publicarea unei versiuni noi nu modifică retroactiv contractele existente.'] },
      ],
    },
  },
  en: {
    privacy: {
      title: 'Privacy policy', description: 'How personal data is collected, used and protected on techcub.ro.', updated: 'Last updated: August 2026',
      sections: [
        { title: '1. Data controller', paragraphs: ['The data controller is {LEGAL_NAME}, tax ID {CUI}, registration number {REGISTRATION}, registered at {ADDRESS}. Privacy enquiries can be sent to <a href="mailto:{EMAIL}">{EMAIL}</a> or {PHONE}.'] },
        { title: '2. Data collected', paragraphs: ['The contact form may collect your name, email address, subject and message. When you contact me by phone, WhatsApp or social media, I process the information you choose to provide. Newsletter subscriptions require an email address.'] },
        { title: '3. Purpose and legal basis', paragraphs: ['Data is used to answer enquiries, prepare and deliver agreed services, send a requested newsletter and meet legal obligations. The legal basis may be pre-contractual steps, contract performance, consent or a legal obligation.'] },
        { title: '4. Providers and transfers', paragraphs: ['The contact form and newsletter may use Resend to deliver messages and manage subscriptions. Technical providers process data only as required to operate the website. Transfers outside the EEA use safeguards recognised under the GDPR.'] },
        { title: '5. Retention', paragraphs: ['Enquiries are retained as needed for the response and contractual relationship, then according to applicable legal periods. Newsletter data is kept until you unsubscribe or withdraw consent.'] },
        { title: '6. Your rights', paragraphs: ['You may request access, correction, deletion, restriction, objection or portability and may withdraw consent. Contact <a href="mailto:{EMAIL}">{EMAIL}</a>. You may also lodge a complaint with the Romanian supervisory authority, <a href="https://www.dataprotection.ro/" target="_blank" rel="noopener noreferrer">ANSPDCP</a>.'] },
        { title: '7. Cookies and analytics', paragraphs: ['Non-essential cookies are not activated without consent when configured. This policy will be updated if new analytics, marketing or integration services change how personal data is processed.'] },
      ],
    },
    terms: {
      title: 'Terms and conditions', description: 'General conditions governing the website and Tech cu Bogdan services.', updated: 'Last updated: August 2026',
      sections: [
        { title: '1. Service provider', paragraphs: ['The services presented on techcub.ro are provided by {LEGAL_NAME}, tax ID {CUI}, registration number {REGISTRATION}, registered at {ADDRESS}. Contact: <a href="mailto:{EMAIL}">{EMAIL}</a>, {PHONE}.'] },
        { title: '2. Website and contract', paragraphs: ['The website presents web development, computer repair, IT support and IT management services. Published information is general and does not by itself constitute a binding offer.', 'A contract is formed when the parties confirm in writing the work, scope, price or calculation method and, where applicable, the delivery date. An accepted quote, order or individual contract prevails over these terms.'] },
        { title: '3. Services and timing', paragraphs: ['Stages, deliverables and recurring services are agreed for each engagement. Additional work requires prior notice and acceptance of its cost. Delivery dates depend on timely access, information, materials and approvals from the client.'] },
        { title: '4. Prices and third-party costs', paragraphs: ['Prices and payment terms are those confirmed to the client. Parts, licences, subscriptions and third-party services are excluded unless expressly stated. Parts are replaced and estimates exceeded only with the client’s approval.'] },
        { title: '5. Client responsibilities', paragraphs: ['The client must provide accurate information, hold the necessary rights over devices, accounts, data and materials, and maintain current backups before an intervention unless backup creation was expressly included.'] },
        { title: '6. Warranty and liability', paragraphs: ['Computer repair labour carries a 30-day commercial warranty without limiting statutory rights. It does not cover unrelated or pre-existing defects, misuse, later third-party intervention or parts supplied by the client.', 'Services are provided within the agreed scope. The provider is not responsible for manufacturer restrictions or third-party service availability. Nothing excludes rights or liability that cannot lawfully be excluded.'] },
        { title: '7. Web development and intellectual property', paragraphs: ['The client is responsible for the legality of supplied materials. Rights in bespoke deliverables are transferred or licensed as stated in the quote and after full payment. Pre-existing components and third-party materials remain subject to their own licences.'] },
        { title: '8. Consumer withdrawal', paragraphs: ['A consumer entering a distance or off-premises service contract may have a 14-day withdrawal right under applicable law. If performance begins during that period at the consumer’s request, a proportionate amount remains payable. The right may be lost after full performance with prior express consent and acknowledgement.'] },
        { title: '9. Complaints and disputes', paragraphs: ['Complaints may be sent to <a href="mailto:{EMAIL}">{EMAIL}</a>. Consumers may contact <a href="https://anpc.ro/" target="_blank" rel="noopener noreferrer">ANPC</a> and use its <a href="https://reclamatiisal.anpc.ro/" target="_blank" rel="noopener noreferrer">alternative dispute resolution platform</a>. Romanian law applies without affecting mandatory consumer protections.'] },
        { title: '10. Updates', paragraphs: ['These terms may be updated when services or laws change. The version accepted when a contract is formed remains applicable to that contract; later publication does not retroactively amend existing contracts.'] },
      ],
    },
  },
} as const;
